# Generated by Django 5.2.10 on 2026-02-01 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, default='', max_length=200)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('push_token', models.CharField(blank=True, default='', max_length=300)),
                ('emergency_type', models.CharField(max_length=50)),
                ('priority', models.CharField(max_length=10)),
                ('message', models.TextField()),
                ('zone', models.CharField(blank=True, default='', max_length=100)),
                ('global_status', models.CharField(default='unknown', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('error', models.TextField(blank=True, default='')),
                ('delivery_id', models.CharField(max_length=64)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='notifications.notificationlog')),
            ],
        ),
    ]
