# Generated by Django 5.2.10 on 2026-02-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverylog',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
