"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.10.

Objectif projet :
- Web simple (UI) qui appelle le noyau POO (core/, mixins/, priority/, etc.)
- SQLite pour la démo
"""

from __future__ import annotations

from pathlib import Path
import sys
import os

# ============================================================
# PATHS : permettre à Django (dans web/) d'importer core/ (racine)
# ============================================================

# BASE_DIR pointe vers .../POO-EXAM1/web
BASE_DIR = Path(__file__).resolve().parent.parent

# PROJECT_ROOT pointe vers .../POO-EXAM1 (le parent de web)
PROJECT_ROOT = BASE_DIR.parent

# Ajoute la racine au PYTHONPATH pour importer core/, mixins/, priority/, etc.
# IMPORTANT : settings.py ne doit PAS importer core.* directement.
sys.path.insert(0, str(PROJECT_ROOT))

# ============================================================
# SÉCURITÉ / DEBUG
# ============================================================

# Pour la démo locale uniquement. Ne jamais exposer ce SECRET_KEY en prod.
SECRET_KEY = "django-insecure-change-this-in-prod"

DEBUG = True

# Local uniquement
ALLOWED_HOSTS = ["127.0.0.1", "localhost"]

# ============================================================
# APPS
# ============================================================

INSTALLED_APPS = [
    # Django built-in
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Votre app UI
    "notifications",
]

# ============================================================
# MIDDLEWARE
# ============================================================

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# ============================================================
# URLS / WSGI
# ============================================================

ROOT_URLCONF = "config.urls"
WSGI_APPLICATION = "config.wsgi.application"

# ============================================================
# TEMPLATES
# ============================================================

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",

        # Optionnel : si tu veux mettre des templates globaux dans web/templates/
        # Sinon, tu peux laisser [], car APP_DIRS=True détecte templates/ dans l'app.
        "DIRS": [BASE_DIR / "templates"],

        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    }
]

# ============================================================
# DATABASE (SQLite pour la démo)
# ============================================================

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# ============================================================
# PASSWORD VALIDATION (tu peux garder par défaut)
# ============================================================

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# ============================================================
# INTERNATIONALIZATION
# ============================================================

# Tu peux mettre "fr-fr" si tu veux UI en français
LANGUAGE_CODE = "fr-fr"

# À Kinshasa ça peut être "Africa/Kinshasa" (optionnel pour la démo)
TIME_ZONE = "Africa/Kinshasa"

USE_I18N = True
USE_TZ = True

# ============================================================
# STATIC FILES
# ============================================================

STATIC_URL = "static/"

# Optionnel : si tu veux un dossier static global web/static/
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# ============================================================
# DEFAULT PK
# ============================================================

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/login/"
